#!/usr/bin/env python3
"""Write web/fixtures/giyim-regression.v1.json from the REAL crawler pipeline run offline on reviewed fixtures
(server/tests/fixtures/discovery_v15). The JS locked regression (web/test-v15-discovery.mjs) evaluates this genuine
crawler output; server/tests/test_discovery_v15.py fails if the committed file is stale.

    python tools/gen-giyim-fixture.py
"""
import io
import contextlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server" / "tests"))
OUT = ROOT / "web" / "fixtures" / "giyim-regression.v1.json"


def build(payload: dict) -> dict:
    import discovery_fixture_run as fx
    return {
        "note": "Generated by tools/gen-giyim-fixture.py from the real crawler pipeline over server/tests/fixtures/discovery_v15. "
                "TEB giyim follows the official terms of teb.com.tr/sizin-icin/giyim-alisveris/ (1–31 Oct 2026: 3.000 TL+ → 120 TL, max 1.200 TL, "
                "Bonus-member merchants); QNB wording follows the official page read on 2026-10-04.",
        "today": fx.TODAY.isoformat(),
        "campaigns": fx.stable_campaigns(payload),
    }


def main() -> int:
    import discovery_fixture_run as fx
    with contextlib.redirect_stdout(io.StringIO()):
        payload = fx.run_pipeline(fx.fixture_sources())
    OUT.write_text(json.dumps(build(payload), ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(payload['campaigns'])} campaigns)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
